### PR TITLE
[#122] Fix wrong order on `hit status` on renames

### LINKED ISSUE #122: Make `hit status` more precise when files are renamed
Sometimes the output of `hit status` is not precise enough when files are renamed. Here is the incorrect output:

```shell
$ hit status
 ➤  Current branch: chshersh/230-Add-AppVeyor-CI
modified  README.md                                  | 0 
modified  appveyor.yml                               | 5 +++--
renamed   examples/Playground.hs -> examples/Main.hs | 4 ++--
modified  tomland.cabal                              | 2 +-
```

Output of used `git` commands:

```shell
$ git diff HEAD --stat
 README.md                           | 5 +++--
 appveyor.yml                        | 4 ++--
 examples/{Playground.hs => Main.hs} | 0
 tomland.cabal                       | 2 +-
 4 files changed, 6 insertions(+), 5 deletions(-)

$ git diff HEAD --name-status
M       README.md
M       appveyor.yml
R100    examples/Playground.hs  examples/Main.hs
M       tomland.cabal
```

cc @crtschin (maybe you have some ideas since you've implemented renamed files support)

### PR DESCRIPTION
**Pull request by crtschin**
Should fix #122.
Was caused due to paths being compacted like:
- `foo/{baz.a => baz.b}`
- `foo/{baz.a => bar/baz.b}`
- `foo/{ => bar}/baz.a`

of which only the second part after the `=>` was picked up previously.
Suggestions or improvements are very welcome!

### CODE REVIEW

File: src/Hit/Git/Status.hs [hunk 1]
```diff
@@ -136,6 +137,34 @@ parseDiffStat = \case
         }
     _ -> Nothing
 
+{- | Attempts to expand shortened paths which can appear in `git diff --stat`.
+Examples of possible paths:
+
+@
+ a.in      => b.out
+ test/{bar => baz}
+ test/{bar => a1{/baz}
```
Comment (chshersh) [inline src/Hit/Git/Status.hs]: Curly braces in this particular example are unbalanced. Is this a typo or `git` outputs in the same format?

File: src/Hit/Git/Status.hs [hunk 2]
```diff
@@ -136,6 +137,34 @@ parseDiffStat = \case
         }
     _ -> Nothing
 
+{- | Attempts to expand shortened paths which can appear in `git diff --stat`.
+Examples of possible paths:
```
Comment (chshersh) [inline src/Hit/Git/Status.hs]: Can you, please, add a few examples on how this function works on different expected inputs? IIUC, documentations only shows expected intputs at the moment.

File: src/Hit/Git/Status.hs [hunk 3]
```diff
@@ -115,18 +115,19 @@ It also handles special case of binary files. Typical raw text returned by @git@
...
+ qux => quux            |   0
 @
 -}
 parseDiffStat :: [Text] -> Maybe DiffStat
 parseDiffStat = \case
     [diffStatFile, diffStatCount, diffStatSigns] -> Just DiffStat{..}
-    _:"=>":diffStatFile:diffStatCount:rest -> Just DiffStat
+    prevFile:"=>":newFile:diffStatCount:rest -> Just DiffStat
         { diffStatSigns = unwords rest
+        , diffStatFile = expandFilePath (unwords [prevFile, "=>", newFile])
```
Comment (chshersh) [inline src/Hit/Git/Status.hs]: I see `unwords` here but the first thing `expandFilePath` does is splits given string by `=>`. I think it can make things simple if `expandFilePath` is given `(Text, Text)` -- a text before arrow and after. Or maybe something different can be done. The main idea is that once we already parsed the string and we have some information, we can use that information and avoid doing necessary work

File: src/Hit/Git/Status.hs (hunk 1 above)
Comment (crtschin) [reply src/Hit/Git/Status.hs]: Yeah, that's what git showed, when the folder was called `a1{`.
