### PR TITLE
[#82] Add force flag to hit fix

### LINKED ISSUE #82: Add --force to `hit fix`

### PR DESCRIPTION
**Pull request by vrom911**
Resolves #82

### CODE REVIEW

File: src/Hit/Git.hs [hunk 1]
```diff
@@ -75,32 +76,34 @@ runCommit (T.strip -> msg) (not -> hasIssue)
...
+runFix msg pushBool = do
     "git" ["add", "."]
     "git" ["commit", "-m", message]
-    runPush False
-    where
-        message = fromMaybe "Fix after review" msg
+    runPush pushBool
+  where
+    message :: Text
+    message = fromMaybe "Fix after review" msg
```
Comment (chshersh) [inline src/Hit/Git.hs]: Can we change it to `Fix` here as well? :slightly_smiling_face:

File: src/Hit/Git.hs [hunk 2]
```diff
@@ -75,32 +76,34 @@ runCommit (T.strip -> msg) (not -> hasIssue)
...
-    runPush True
+    runPush Force
 
 -- | @hit push@ command.
-runPush :: Bool -> IO ()
+runPush :: PushBool -> IO ()
 runPush isForce = getCurrentBranch >>= \branch ->
     "git" $ ["push", "--set-upstream", "origin", branch]
-         ++ ["--force" | isForce]
+         ++ ["--force" | isForce == Force]
```
Comment (chshersh) [inline src/Hit/Git.hs]: Oh, this is very nice!
